---
- name: include_tasks | deb.yml
  ansible.builtin.include_tasks: deb.yml
  when: ansible_os_family == "Debian"

- name: include_tasks | rpm.yml
  ansible.builtin.include_tasks: rpm.yml
  when: ansible_os_family == "RedHat"

- name: VECTOR | Using vector template
  # become: true
  ansible.builtin.template:
    src: "templates/vector.yml.j2"
    dest: "{{ vector_conf_dir }}/vector.toml"
    mode: "0644"
  notify: Restart Vector service