---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  vars:
    vector_config_path: /etc/vector/vector.toml
  tasks:
    - name: Validation Vector configuration
      ansible.builtin.command: "vector validate --no-environment --config-toml {{ vector_config_path }}"
      changed_when: false
      register: vector_validate
    - name: Get Vector version
      ansible.builtin.command: "vector -V"
      register: vector_version
    - name: Assert Vector instalation
      ansible.builtin.assert:
        that: "'{{ vector_version.rc }}' == '0'"
    - name: Get Vector validation
      ansible.builtin.command: "vector validate"
      register: vector_check
    - name: Assert Vector validation
      ansible.builtin.assert:
        that: "'{{ vector_check.rc }}' == '0'"